# Generated by Django 5.0.7 on 2024-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_alter_cart_create_date_cartitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='categories',
            new_name='product',
        ),
    ]
